models:
  - model: /path/to/WildMarcoroni-Variant1-7B-model-west-first-nm64_256/
    parameters:
      weight: 1.2
  - model: /path/to/WestSeverus-7B-DPO-v2-model-west-first-nm64_256/
    parameters:
      weight: 1.2
         
merge_method: task_arithmetic
dtype: float16
base_model:  /path/to/model/Mistral-7b-v0.1-float16
